config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users, :controllers => {:registrations => 'user/registrations'}

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friends', to: 'users#search'
  get 'search_stocks', to: 'stocks#search'
  
  resources :user_stocks, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :friendships
   

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :user
    belongs_to :friend, :class_name => 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks
    
    def self.find_by_ticker(ticker_sumbol)
        where(ticker: ticker_sumbol).first
    end

    def self.new_from_lookup(ticker_symbol)
        begin
            looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
            price = strip_commas(looked_up_stock.l)
            new(name: looked_up_stock.name, ticker: looked_up_stock.symbol, last_price: price)      
        rescue Exception => e
            return nil
        end
    end
    def self.strip_commas(number)
        number.gsub(",","")
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end
  def stock_already_added(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end

  def under_stock_limit?
    (user_stocks.count < 10)
  end

  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added(ticker_symbol)
  end

  def self.search(params)
    params.strip
    params.downcase!
    to_send_back = (search_by_first_name(params) + search_by_last_name(params) +
                    search_by_email(params)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.search_by_first_name(params)
    matches('first_name', params)
  end

  def self.search_by_last_name(params)
    matches('last_name', params)
  end

  def self.search_by_email(params)
    matches('email', params)
  end

  def self.matches(field_name, params)
    User.where("#{field_name} like?", "%#{params}%")
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
                
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    
    def search
        if params[:stock].blank?
            flash.now[:danger] = "Please enter something?"
        else
            @stock = Stock.new_from_lookup( params[:stock] )
            flash.now[:danger] = "Please enter some valid stuff?" unless @stock
        end                  
        respond_to do |format|
            format.js { render partial: 'users/result'}
          end    
    end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])        
    end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create
        stock = Stock.find_by_ticker(params[:stock_ticker])
        if stock.blank?
          stock = Stock.new_from_lookup(params[:stock_ticker])
          stock.save
        end
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:success] = "Stock #{@user_stock.stock.name} added to your portfolio"
        redirect_to my_portfolio_path 
    end

    def destroy
        stock = Stock.find(params[:id])
        @user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
        @user_stock.delete
        flash[:success] = "The stock was successfully deleted"
        redirect_to my_portfolio_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def my_portfolio
      @user = current_user
      @user_stocks = current_user.stocks         
    end

    def my_friends
        @friendships = current_user.friends
    end

    def search
        @users = User.search(params[:search_param])
        render json: @users
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stock_helper.rb
module UserStockHelper
end

app/views/friends/_lookup.html.erb
<h1>My frineds</h1>
<h3>Search for Friends</h3>

<div id="friend-lookup">
    <%= form_tag search_friends_path, remote: true, method: :get, id: "stock-lookup-form" do %>
        <div class="form-group row no-padding text-center col-md-12">
            <div class="col-md-10">
                <%= text_field_tag :search, params[:search], placeholder: "Search using name or email", autofocus: true, 
                                           class: "form-control search-box input-lg"  %>
            </div>
            <div class="col-md-2">
               <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
                    <i class="fa fa-search"></i> Search  
               <% end %>
            </div>
        </div>
    <% end %>
</div> 

app/views/layouts/_nav.html.erb
<div class="navbar navbar-default navbar-static-top">
        <div class="container">
            <%= link_to  "Stock App", root_path, class: "navbar-brand" %>
          <% if current_user %>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="navbar-collapse collapse navbar-responsive-collapse">
              <ul class="nav navbar-nav col-md-6">
                <li><%= link_to "My Portfolio", my_portfolio_path  %></li>
                <li><%= link_to "My Profile", edit_registration_path(current_user)  %></li>
                <li><%= link_to "Friends list", my_friends_path  %></li>
              </ul>
              <ul class="nav navbar-right col-md-4">
                <li class="col-md-8 user-name text-right">
                  <i class="fa fa-user"></i>
                  <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
                </li>
                <li class="col-md-4 logout"><%= link_to  "Logout", destroy_user_session_path, method: :delete, class: "btn btn-xs btn-danger" %></li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "StockApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <%= render  "layouts/nav" %>
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/home.html.erb
<h1>This is the home page. You shall be welcomed</h1>

app/views/stocks/_list.html.erb
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Symbol</th>
            <th>Current Price</th>
            <% if @user.id == current_user.id %>
              <th>Action</th>
            <% end %>
        </tr>
    </thead>
    <tbody>
        <% @user_stocks.each do |us| %>
         <tr>        
           <td><%= us.name %></td>
           <td><%=us.ticker %></td>
           <td><%=us.last_price %></td>
           <% if @user.id == current_user.id %>
             <td><%= link_to  "Delete", user_stock_path(us), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" %></td>
           <% end %>
         </tr>
        <%end%>   
    </tbody>
</table>

app/views/users/_result.js.erb
$('#results').html("<%= j(render 'users/results.html') %>")

app/views/users/_results.html.erb
<% if params[:action] == 'search' %>
    <div class="result-block">
     <%= bootstrap_flash %>
    </div>
<% end %>    
<% if @stock %>
<div class="well result-block">
    <strong>Symbol: </strong><%= @stock.ticker%>
    <strong>Name: </strong><%= @stock.name%>
    <strong>Price: </strong><%= @stock.last_price%>
    <% if current_user.can_add_stock?(@stock.ticker) %>
        <%= link_to  "Add to my stocks", user_stocks_path(user: current_user, stock_ticker: @stock.ticker), class: "btn bln-lg btn-danger", method: :post %>
    <% else %>
        <span class="btn btn-danger">
            you can't add the stock because you already
            <% if current_user.stock_already_added(@stock.ticker) %>
                have this stock
            <% else %>
                exceeded your limits
            <% end %>
        </span>
    <% end %>

</div>
<% end %>

app/views/users/my_friends.html.erb
<%= render 'friends/lookup' %>

<% if @friendships.size > 0 %>
<table class="table table-striped">
        <thead>
            <tr>
                <th colspan="3" class="page-header">
                    <h2>My Friends</h2>
                </th>
            </tr>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <% @friendships.each do |fr| %>
             <tr>        
               <td><%= fr.full_name %></td>
               <td><%=fr.email %></td>
               <td><%= link_to  "View Profile", user_path(fr), class: "btn btn-xs btn-primary" %></td>
               <td><%= link_to  "Remove", friendship_path(fr), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" %></td>
             </tr>
            <%end%>   
        </tbody>
    </table>
<% else %>
   <div class="row col-lg-12">
       <p class="lead">You have no friends, please add some</p>
  </div> 
<%end%>

app/views/users/my_portfolio.html.erb
<h1>This is gonna be my portfolio</h1>

<h3>Search for stocks</h3>

<div id="stock-lookup">
    <%= form_tag search_stocks_path, remote: true, method: :get, id: "stock-lookup-form" do %>
        <div class="form-group row no-padding text-center col-md-12">
            <div class="col-md-10">
                <%= text_field_tag :stock, params[:stock], placeholder: "Stock Ticker Symbol", autofocus: true, 
                                           class: "form-control search-box input-lg"  %>
            </div>
            <div class="col-md-2">
               <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
                    <i class="fa fa-search"></i> Look up a stock  
               <% end %>
            </div>
        </div>
    <% end %>
</div> 
<div id="results">
    <%= render  "results" %>
</div>
<%= render "stocks/list" %>